version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
